[app]
address = "0.0.0.0:9000"
root_url = "https://lebere.up.railway.app"

[db]
host = "${LISTMONK_db_host}"
port = "${LISTMONK_db_port}"
user = "${LISTMONK_db_user}"
password = "${LISTMONK_db_password}"
database = "${LISTMONK_db_database}"
ssl_mode = "disable"

[messengers]
timeout = "30s"

[[messengers.postback]]
name = "gmail_api_railway"
enabled = true
url = "https://listmonk-gmail-messenger-production.up.railway.app/postback"
username = "${LISTMONK_POSTBACK_USER}"
password = "${LISTMONK_POSTBACK_PASS}"

[media]
provider = "filesystem"
upload_path = "/listmonk/uploads"
